# Generated by Django 5.2 on 2025-06-06 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='creator_name',
        ),
        migrations.AddField(
            model_name='video',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='videos.creator'),
            preserve_default=False,
        ),
    ]
