# Generated by Django 5.2 on 2025-06-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_video_creator_name_video_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='creator_image',
            field=models.ImageField(blank=True, null=True, upload_to='creator_image/'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumb_image',
            field=models.ImageField(blank=True, null=True, upload_to='thumb_image/'),
        ),
    ]
