# Generated by Django 5.2 on 2025-06-08 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_creator_creator_image_video_thumb_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='creator_image',
            new_name='profile_image',
        ),
    ]
