# Generated by Django 5.2 on 2025-06-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_rename_creator_image_creator_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='creator',
            name='about_us',
            field=models.TextField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='creator',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
