# Generated by Django 5.2 on 2025-06-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_banner_alter_creator_about_us_alter_creator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
