# Generated by Django 5.2 on 2025-06-14 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_creator_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='phone_number',
        ),
    ]
