# Generated by Django 5.2 on 2025-06-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_remove_creator_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
