# Generated by Django 5.2 on 2025-05-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='new_user',
            field=models.BooleanField(default=True),
        ),
    ]
