# Generated by Django 5.2 on 2025-06-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_otp_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
